//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.17 at 09:13:10 PM WEST 
//


package messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import models.Answers;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}questionBody"/>
 *         &lt;element ref="{}answers"/>
 *       &lt;/sequence>
 *       &lt;attribute name="sessionNumer" type="{http://www.w3.org/2001/XMLSchema}short" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "questionBody",
    "answers"
})
@XmlRootElement(name = "addQuestionRequest")
public class AddQuestionRequest {

    @XmlElement(required = true)
    protected String questionBody;
    @XmlElement(required = true)
    protected Answers answers;
    @XmlAttribute(name = "sessionNumer")
    protected Short sessionNumer;

    /**
     * Gets the value of the questionBody property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuestionBody() {
        return questionBody;
    }

    /**
     * Sets the value of the questionBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuestionBody(String value) {
        this.questionBody = value;
    }

    /**
     * Gets the value of the answers property.
     * 
     * @return
     *     possible object is
     *     {@link Answers }
     *     
     */
    public Answers getAnswers() {
        return answers;
    }

    /**
     * Sets the value of the answers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Answers }
     *     
     */
    public void setAnswers(Answers value) {
        this.answers = value;
    }

    /**
     * Gets the value of the sessionNumer property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getSessionNumer() {
        return sessionNumer;
    }

    /**
     * Sets the value of the sessionNumer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setSessionNumer(Short value) {
        this.sessionNumer = value;
    }

}
