//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.17 at 01:00:12 AM WEST 
//


package messages;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the messages package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: messages
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XmlDB }
     * 
     */
    public XmlDB createXmlDB() {
        return new XmlDB();
    }

    /**
     * Create an instance of {@link XmlDB.Stats }
     * 
     */
    public XmlDB.Stats createXmlDBStats() {
        return new XmlDB.Stats();
    }

    /**
     * Create an instance of {@link XmlDB.Stats.Session }
     * 
     */
    public XmlDB.Stats.Session createXmlDBStatsSession() {
        return new XmlDB.Stats.Session();
    }

    /**
     * Create an instance of {@link XmlDB.Stats.Session.QuestionsAsked }
     * 
     */
    public XmlDB.Stats.Session.QuestionsAsked createXmlDBStatsSessionQuestionsAsked() {
        return new XmlDB.Stats.Session.QuestionsAsked();
    }

    /**
     * Create an instance of {@link XmlDB.Stats.Session.QuestionsAsked.QAsked }
     * 
     */
    public XmlDB.Stats.Session.QuestionsAsked.QAsked createXmlDBStatsSessionQuestionsAskedQAsked() {
        return new XmlDB.Stats.Session.QuestionsAsked.QAsked();
    }

    /**
     * Create an instance of {@link XmlDB.Users }
     * 
     */
    public XmlDB.Users createXmlDBUsers() {
        return new XmlDB.Users();
    }

    /**
     * Create an instance of {@link XmlDB.Questions }
     * 
     */
    public XmlDB.Questions createXmlDBQuestions() {
        return new XmlDB.Questions();
    }

    /**
     * Create an instance of {@link XmlDB.Questions.Question }
     * 
     */
    public XmlDB.Questions.Question createXmlDBQuestionsQuestion() {
        return new XmlDB.Questions.Question();
    }

    /**
     * Create an instance of {@link XmlDB.Questions.Question.Answers }
     * 
     */
    public XmlDB.Questions.Question.Answers createXmlDBQuestionsQuestionAnswers() {
        return new XmlDB.Questions.Question.Answers();
    }

    /**
     * Create an instance of {@link XmlDB.Stats.Session.QuestionsAsked.QAsked.CorrectAnswer }
     * 
     */
    public XmlDB.Stats.Session.QuestionsAsked.QAsked.CorrectAnswer createXmlDBStatsSessionQuestionsAskedQAskedCorrectAnswer() {
        return new XmlDB.Stats.Session.QuestionsAsked.QAsked.CorrectAnswer();
    }

    /**
     * Create an instance of {@link XmlDB.Stats.Session.QuestionsAsked.QAsked.WrongAnswer }
     * 
     */
    public XmlDB.Stats.Session.QuestionsAsked.QAsked.WrongAnswer createXmlDBStatsSessionQuestionsAskedQAskedWrongAnswer() {
        return new XmlDB.Stats.Session.QuestionsAsked.QAsked.WrongAnswer();
    }

    /**
     * Create an instance of {@link XmlDB.Users.User }
     * 
     */
    public XmlDB.Users.User createXmlDBUsersUser() {
        return new XmlDB.Users.User();
    }

    /**
     * Create an instance of {@link XmlDB.Questions.Question.Answers.Answer }
     * 
     */
    public XmlDB.Questions.Question.Answers.Answer createXmlDBQuestionsQuestionAnswersAnswer() {
        return new XmlDB.Questions.Question.Answers.Answer();
    }

}
