//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.17 at 07:02:32 PM WEST 
//


package messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="refIdUser" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="refIdQ" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="allStudents" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="sessionNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "requestQuestionRequest")
public class RequestQuestionRequest {

    @XmlAttribute(name = "refIdUser")
    protected Integer refIdUser;
    @XmlAttribute(name = "refIdQ", required = true)
    protected int refIdQ;
    @XmlAttribute(name = "allStudents", required = true)
    protected boolean allStudents;
    @XmlAttribute(name = "sessionNumber", required = true)
    protected int sessionNumber;

    /**
     * Gets the value of the refIdUser property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRefIdUser() {
        return refIdUser;
    }

    /**
     * Sets the value of the refIdUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRefIdUser(Integer value) {
        this.refIdUser = value;
    }

    /**
     * Gets the value of the refIdQ property.
     * 
     */
    public int getRefIdQ() {
        return refIdQ;
    }

    /**
     * Sets the value of the refIdQ property.
     * 
     */
    public void setRefIdQ(int value) {
        this.refIdQ = value;
    }

    /**
     * Gets the value of the allStudents property.
     * 
     */
    public boolean isAllStudents() {
        return allStudents;
    }

    /**
     * Sets the value of the allStudents property.
     * 
     */
    public void setAllStudents(boolean value) {
        this.allStudents = value;
    }

    /**
     * Gets the value of the sessionNumber property.
     * 
     */
    public int getSessionNumber() {
        return sessionNumber;
    }

    /**
     * Sets the value of the sessionNumber property.
     * 
     */
    public void setSessionNumber(int value) {
        this.sessionNumber = value;
    }

}
