//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.14 at 10:24:31 PM WEST 
//


package messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}answer"/>
 *       &lt;/sequence>
 *       &lt;attribute name="refIdUser" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="refIdQ" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="sessionNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "answer"
})
@XmlRootElement(name = "sendAnswerRequest")
public class SendAnswerRequest {

    @XmlElement(required = true)
    protected String answer;
    @XmlAttribute(name = "refIdUser", required = true)
    protected int refIdUser;
    @XmlAttribute(name = "refIdQ", required = true)
    protected int refIdQ;
    @XmlAttribute(name = "sessionNumber", required = true)
    protected int sessionNumber;

    /**
     * Gets the value of the answer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * Sets the value of the answer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnswer(String value) {
        this.answer = value;
    }

    /**
     * Gets the value of the refIdUser property.
     * 
     */
    public int getRefIdUser() {
        return refIdUser;
    }

    /**
     * Sets the value of the refIdUser property.
     * 
     */
    public void setRefIdUser(int value) {
        this.refIdUser = value;
    }

    /**
     * Gets the value of the refIdQ property.
     * 
     */
    public int getRefIdQ() {
        return refIdQ;
    }

    /**
     * Sets the value of the refIdQ property.
     * 
     */
    public void setRefIdQ(int value) {
        this.refIdQ = value;
    }

    /**
     * Gets the value of the sessionNumber property.
     * 
     */
    public int getSessionNumber() {
        return sessionNumber;
    }

    /**
     * Sets the value of the sessionNumber property.
     * 
     */
    public void setSessionNumber(int value) {
        this.sessionNumber = value;
    }

}
