//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.17 at 12:11:13 AM WEST 
//


package messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}numOfQuestionsAsked"/>
 *         &lt;element ref="{}numOfQuestionsAnswered"/>
 *         &lt;element ref="{}questionsAsked"/>
 *       &lt;/sequence>
 *       &lt;attribute name="refIdUser" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="idS" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "numOfQuestionsAsked",
    "numOfQuestionsAnswered",
    "questionsAsked"
})
@XmlRootElement(name = "session")
public class Session {

    protected int numOfQuestionsAsked;
    protected int numOfQuestionsAnswered;
    @XmlElement(required = true)
    protected QuestionsAsked questionsAsked;
    @XmlAttribute(name = "refIdUser", required = true)
    protected int refIdUser;
    @XmlAttribute(name = "idS", required = true)
    protected int idS;

    /**
     * Gets the value of the numOfQuestionsAsked property.
     * 
     */
    public int getNumOfQuestionsAsked() {
        return numOfQuestionsAsked;
    }

    /**
     * Sets the value of the numOfQuestionsAsked property.
     * 
     */
    public void setNumOfQuestionsAsked(int value) {
        this.numOfQuestionsAsked = value;
    }

    /**
     * Gets the value of the numOfQuestionsAnswered property.
     * 
     */
    public int getNumOfQuestionsAnswered() {
        return numOfQuestionsAnswered;
    }

    /**
     * Sets the value of the numOfQuestionsAnswered property.
     * 
     */
    public void setNumOfQuestionsAnswered(int value) {
        this.numOfQuestionsAnswered = value;
    }

    /**
     * Gets the value of the questionsAsked property.
     * 
     * @return
     *     possible object is
     *     {@link QuestionsAsked }
     *     
     */
    public QuestionsAsked getQuestionsAsked() {
        return questionsAsked;
    }

    /**
     * Sets the value of the questionsAsked property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuestionsAsked }
     *     
     */
    public void setQuestionsAsked(QuestionsAsked value) {
        this.questionsAsked = value;
    }

    /**
     * Gets the value of the refIdUser property.
     * 
     */
    public int getRefIdUser() {
        return refIdUser;
    }

    /**
     * Sets the value of the refIdUser property.
     * 
     */
    public void setRefIdUser(int value) {
        this.refIdUser = value;
    }

    /**
     * Gets the value of the idS property.
     * 
     */
    public int getIdS() {
        return idS;
    }

    /**
     * Sets the value of the idS property.
     * 
     */
    public void setIdS(int value) {
        this.idS = value;
    }

}
