//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.17 at 01:00:12 AM WEST 
//


package messages;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="questions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="question" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="questionBody" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="answers">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="answer" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="answerBody" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="bool" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="idQ" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="refIdUser" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="users">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="user" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="birthDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="idUser" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="role" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="stats">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="session" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="numOfQuestionsAsked" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="numOfQuestionsAnswered" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="questionsAsked">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="qAsked">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="correctAnswer">
 *                                                   &lt;complexType>
 *                                                     &lt;simpleContent>
 *                                                       &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                                         &lt;attribute name="numOfCorrectAnswers" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                                       &lt;/extension>
 *                                                     &lt;/simpleContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                                 &lt;element name="wrongAnswer">
 *                                                   &lt;complexType>
 *                                                     &lt;simpleContent>
 *                                                       &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                                         &lt;attribute name="numOfWrongAnswers" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                                       &lt;/extension>
 *                                                     &lt;/simpleContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="idQAsked" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                               &lt;attribute name="refIdQ" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="idS" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="refIdUser" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "questions",
    "users",
    "stats"
})
@XmlRootElement(name = "xmlDB")
public class XmlDB {

    @XmlElement(required = true)
    protected XmlDB.Questions questions;
    @XmlElement(required = true)
    protected XmlDB.Users users;
    @XmlElement(required = true)
    protected XmlDB.Stats stats;

    /**
     * Gets the value of the questions property.
     * 
     * @return
     *     possible object is
     *     {@link XmlDB.Questions }
     *     
     */
    public XmlDB.Questions getQuestions() {
        return questions;
    }

    /**
     * Sets the value of the questions property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlDB.Questions }
     *     
     */
    public void setQuestions(XmlDB.Questions value) {
        this.questions = value;
    }

    /**
     * Gets the value of the users property.
     * 
     * @return
     *     possible object is
     *     {@link XmlDB.Users }
     *     
     */
    public XmlDB.Users getUsers() {
        return users;
    }

    /**
     * Sets the value of the users property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlDB.Users }
     *     
     */
    public void setUsers(XmlDB.Users value) {
        this.users = value;
    }

    /**
     * Gets the value of the stats property.
     * 
     * @return
     *     possible object is
     *     {@link XmlDB.Stats }
     *     
     */
    public XmlDB.Stats getStats() {
        return stats;
    }

    /**
     * Sets the value of the stats property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlDB.Stats }
     *     
     */
    public void setStats(XmlDB.Stats value) {
        this.stats = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="question" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="questionBody" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="answers">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="answer" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="answerBody" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="bool" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="idQ" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="refIdUser" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "question"
    })
    public static class Questions {

        protected List<XmlDB.Questions.Question> question;

        /**
         * Gets the value of the question property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the question property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getQuestion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XmlDB.Questions.Question }
         * 
         * 
         */
        public List<XmlDB.Questions.Question> getQuestion() {
            if (question == null) {
                question = new ArrayList<XmlDB.Questions.Question>();
            }
            return this.question;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="questionBody" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="answers">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="answer" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="answerBody" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                           &lt;attribute name="bool" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="idQ" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="refIdUser" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "questionBody",
            "answers"
        })
        public static class Question {

            @XmlElement(required = true)
            protected String questionBody;
            @XmlElement(required = true)
            protected XmlDB.Questions.Question.Answers answers;
            @XmlAttribute(name = "idQ")
            protected Byte idQ;
            @XmlAttribute(name = "refIdUser")
            protected Byte refIdUser;

            /**
             * Gets the value of the questionBody property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getQuestionBody() {
                return questionBody;
            }

            /**
             * Sets the value of the questionBody property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setQuestionBody(String value) {
                this.questionBody = value;
            }

            /**
             * Gets the value of the answers property.
             * 
             * @return
             *     possible object is
             *     {@link XmlDB.Questions.Question.Answers }
             *     
             */
            public XmlDB.Questions.Question.Answers getAnswers() {
                return answers;
            }

            /**
             * Sets the value of the answers property.
             * 
             * @param value
             *     allowed object is
             *     {@link XmlDB.Questions.Question.Answers }
             *     
             */
            public void setAnswers(XmlDB.Questions.Question.Answers value) {
                this.answers = value;
            }

            /**
             * Gets the value of the idQ property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getIdQ() {
                return idQ;
            }

            /**
             * Sets the value of the idQ property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setIdQ(Byte value) {
                this.idQ = value;
            }

            /**
             * Gets the value of the refIdUser property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getRefIdUser() {
                return refIdUser;
            }

            /**
             * Sets the value of the refIdUser property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setRefIdUser(Byte value) {
                this.refIdUser = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="answer" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="answerBody" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *                 &lt;attribute name="bool" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "answer"
            })
            public static class Answers {

                protected List<XmlDB.Questions.Question.Answers.Answer> answer;

                /**
                 * Gets the value of the answer property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the answer property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getAnswer().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link XmlDB.Questions.Question.Answers.Answer }
                 * 
                 * 
                 */
                public List<XmlDB.Questions.Question.Answers.Answer> getAnswer() {
                    if (answer == null) {
                        answer = new ArrayList<XmlDB.Questions.Question.Answers.Answer>();
                    }
                    return this.answer;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="answerBody" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *       &lt;attribute name="bool" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "answerBody"
                })
                public static class Answer {

                    @XmlElement(required = true)
                    protected String answerBody;
                    @XmlAttribute(name = "bool")
                    protected String bool;

                    /**
                     * Gets the value of the answerBody property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getAnswerBody() {
                        return answerBody;
                    }

                    /**
                     * Sets the value of the answerBody property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setAnswerBody(String value) {
                        this.answerBody = value;
                    }

                    /**
                     * Gets the value of the bool property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getBool() {
                        return bool;
                    }

                    /**
                     * Sets the value of the bool property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setBool(String value) {
                        this.bool = value;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="session" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="numOfQuestionsAsked" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="numOfQuestionsAnswered" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="questionsAsked">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="qAsked">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="correctAnswer">
     *                                         &lt;complexType>
     *                                           &lt;simpleContent>
     *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                               &lt;attribute name="numOfCorrectAnswers" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                                             &lt;/extension>
     *                                           &lt;/simpleContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                       &lt;element name="wrongAnswer">
     *                                         &lt;complexType>
     *                                           &lt;simpleContent>
     *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                               &lt;attribute name="numOfWrongAnswers" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                                             &lt;/extension>
     *                                           &lt;/simpleContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="idQAsked" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                                     &lt;attribute name="refIdQ" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="idS" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="refIdUser" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "session"
    })
    public static class Stats {

        protected List<XmlDB.Stats.Session> session;

        /**
         * Gets the value of the session property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the session property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSession().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XmlDB.Stats.Session }
         * 
         * 
         */
        public List<XmlDB.Stats.Session> getSession() {
            if (session == null) {
                session = new ArrayList<XmlDB.Stats.Session>();
            }
            return this.session;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="numOfQuestionsAsked" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="numOfQuestionsAnswered" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="questionsAsked">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="qAsked">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="correctAnswer">
         *                               &lt;complexType>
         *                                 &lt;simpleContent>
         *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                                     &lt;attribute name="numOfCorrectAnswers" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *                                   &lt;/extension>
         *                                 &lt;/simpleContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                             &lt;element name="wrongAnswer">
         *                               &lt;complexType>
         *                                 &lt;simpleContent>
         *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                                     &lt;attribute name="numOfWrongAnswers" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *                                   &lt;/extension>
         *                                 &lt;/simpleContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                           &lt;attribute name="idQAsked" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *                           &lt;attribute name="refIdQ" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="idS" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="refIdUser" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "numOfQuestionsAsked",
            "numOfQuestionsAnswered",
            "questionsAsked"
        })
        public static class Session {

            protected byte numOfQuestionsAsked;
            protected byte numOfQuestionsAnswered;
            @XmlElement(required = true)
            protected XmlDB.Stats.Session.QuestionsAsked questionsAsked;
            @XmlAttribute(name = "idS")
            protected Byte idS;
            @XmlAttribute(name = "refIdUser")
            protected Byte refIdUser;

            /**
             * Gets the value of the numOfQuestionsAsked property.
             * 
             */
            public byte getNumOfQuestionsAsked() {
                return numOfQuestionsAsked;
            }

            /**
             * Sets the value of the numOfQuestionsAsked property.
             * 
             */
            public void setNumOfQuestionsAsked(byte value) {
                this.numOfQuestionsAsked = value;
            }

            /**
             * Gets the value of the numOfQuestionsAnswered property.
             * 
             */
            public byte getNumOfQuestionsAnswered() {
                return numOfQuestionsAnswered;
            }

            /**
             * Sets the value of the numOfQuestionsAnswered property.
             * 
             */
            public void setNumOfQuestionsAnswered(byte value) {
                this.numOfQuestionsAnswered = value;
            }

            /**
             * Gets the value of the questionsAsked property.
             * 
             * @return
             *     possible object is
             *     {@link XmlDB.Stats.Session.QuestionsAsked }
             *     
             */
            public XmlDB.Stats.Session.QuestionsAsked getQuestionsAsked() {
                return questionsAsked;
            }

            /**
             * Sets the value of the questionsAsked property.
             * 
             * @param value
             *     allowed object is
             *     {@link XmlDB.Stats.Session.QuestionsAsked }
             *     
             */
            public void setQuestionsAsked(XmlDB.Stats.Session.QuestionsAsked value) {
                this.questionsAsked = value;
            }

            /**
             * Gets the value of the idS property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getIdS() {
                return idS;
            }

            /**
             * Sets the value of the idS property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setIdS(Byte value) {
                this.idS = value;
            }

            /**
             * Gets the value of the refIdUser property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getRefIdUser() {
                return refIdUser;
            }

            /**
             * Sets the value of the refIdUser property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setRefIdUser(Byte value) {
                this.refIdUser = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="qAsked">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="correctAnswer">
             *                     &lt;complexType>
             *                       &lt;simpleContent>
             *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                           &lt;attribute name="numOfCorrectAnswers" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *                         &lt;/extension>
             *                       &lt;/simpleContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                   &lt;element name="wrongAnswer">
             *                     &lt;complexType>
             *                       &lt;simpleContent>
             *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                           &lt;attribute name="numOfWrongAnswers" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *                         &lt;/extension>
             *                       &lt;/simpleContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *                 &lt;attribute name="idQAsked" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *                 &lt;attribute name="refIdQ" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "qAsked"
            })
            public static class QuestionsAsked {

                @XmlElement(required = true)
                protected XmlDB.Stats.Session.QuestionsAsked.QAsked qAsked;

                /**
                 * Gets the value of the qAsked property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XmlDB.Stats.Session.QuestionsAsked.QAsked }
                 *     
                 */
                public XmlDB.Stats.Session.QuestionsAsked.QAsked getQAsked() {
                    return qAsked;
                }

                /**
                 * Sets the value of the qAsked property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XmlDB.Stats.Session.QuestionsAsked.QAsked }
                 *     
                 */
                public void setQAsked(XmlDB.Stats.Session.QuestionsAsked.QAsked value) {
                    this.qAsked = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="correctAnswer">
                 *           &lt;complexType>
                 *             &lt;simpleContent>
                 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *                 &lt;attribute name="numOfCorrectAnswers" type="{http://www.w3.org/2001/XMLSchema}byte" />
                 *               &lt;/extension>
                 *             &lt;/simpleContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *         &lt;element name="wrongAnswer">
                 *           &lt;complexType>
                 *             &lt;simpleContent>
                 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *                 &lt;attribute name="numOfWrongAnswers" type="{http://www.w3.org/2001/XMLSchema}byte" />
                 *               &lt;/extension>
                 *             &lt;/simpleContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *       &lt;attribute name="idQAsked" type="{http://www.w3.org/2001/XMLSchema}byte" />
                 *       &lt;attribute name="refIdQ" type="{http://www.w3.org/2001/XMLSchema}byte" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "correctAnswer",
                    "wrongAnswer"
                })
                public static class QAsked {

                    @XmlElement(required = true)
                    protected XmlDB.Stats.Session.QuestionsAsked.QAsked.CorrectAnswer correctAnswer;
                    @XmlElement(required = true)
                    protected XmlDB.Stats.Session.QuestionsAsked.QAsked.WrongAnswer wrongAnswer;
                    @XmlAttribute(name = "idQAsked")
                    protected Byte idQAsked;
                    @XmlAttribute(name = "refIdQ")
                    protected Byte refIdQ;

                    /**
                     * Gets the value of the correctAnswer property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link XmlDB.Stats.Session.QuestionsAsked.QAsked.CorrectAnswer }
                     *     
                     */
                    public XmlDB.Stats.Session.QuestionsAsked.QAsked.CorrectAnswer getCorrectAnswer() {
                        return correctAnswer;
                    }

                    /**
                     * Sets the value of the correctAnswer property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link XmlDB.Stats.Session.QuestionsAsked.QAsked.CorrectAnswer }
                     *     
                     */
                    public void setCorrectAnswer(XmlDB.Stats.Session.QuestionsAsked.QAsked.CorrectAnswer value) {
                        this.correctAnswer = value;
                    }

                    /**
                     * Gets the value of the wrongAnswer property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link XmlDB.Stats.Session.QuestionsAsked.QAsked.WrongAnswer }
                     *     
                     */
                    public XmlDB.Stats.Session.QuestionsAsked.QAsked.WrongAnswer getWrongAnswer() {
                        return wrongAnswer;
                    }

                    /**
                     * Sets the value of the wrongAnswer property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link XmlDB.Stats.Session.QuestionsAsked.QAsked.WrongAnswer }
                     *     
                     */
                    public void setWrongAnswer(XmlDB.Stats.Session.QuestionsAsked.QAsked.WrongAnswer value) {
                        this.wrongAnswer = value;
                    }

                    /**
                     * Gets the value of the idQAsked property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Byte }
                     *     
                     */
                    public Byte getIdQAsked() {
                        return idQAsked;
                    }

                    /**
                     * Sets the value of the idQAsked property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Byte }
                     *     
                     */
                    public void setIdQAsked(Byte value) {
                        this.idQAsked = value;
                    }

                    /**
                     * Gets the value of the refIdQ property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Byte }
                     *     
                     */
                    public Byte getRefIdQ() {
                        return refIdQ;
                    }

                    /**
                     * Sets the value of the refIdQ property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Byte }
                     *     
                     */
                    public void setRefIdQ(Byte value) {
                        this.refIdQ = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;simpleContent>
                     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                     *       &lt;attribute name="numOfCorrectAnswers" type="{http://www.w3.org/2001/XMLSchema}byte" />
                     *     &lt;/extension>
                     *   &lt;/simpleContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "value"
                    })
                    public static class CorrectAnswer {

                        @XmlValue
                        protected String value;
                        @XmlAttribute(name = "numOfCorrectAnswers")
                        protected Byte numOfCorrectAnswers;

                        /**
                         * Gets the value of the value property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getValue() {
                            return value;
                        }

                        /**
                         * Sets the value of the value property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setValue(String value) {
                            this.value = value;
                        }

                        /**
                         * Gets the value of the numOfCorrectAnswers property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link Byte }
                         *     
                         */
                        public Byte getNumOfCorrectAnswers() {
                            return numOfCorrectAnswers;
                        }

                        /**
                         * Sets the value of the numOfCorrectAnswers property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link Byte }
                         *     
                         */
                        public void setNumOfCorrectAnswers(Byte value) {
                            this.numOfCorrectAnswers = value;
                        }

                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;simpleContent>
                     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                     *       &lt;attribute name="numOfWrongAnswers" type="{http://www.w3.org/2001/XMLSchema}byte" />
                     *     &lt;/extension>
                     *   &lt;/simpleContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "value"
                    })
                    public static class WrongAnswer {

                        @XmlValue
                        protected String value;
                        @XmlAttribute(name = "numOfWrongAnswers")
                        protected Byte numOfWrongAnswers;

                        /**
                         * Gets the value of the value property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getValue() {
                            return value;
                        }

                        /**
                         * Sets the value of the value property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setValue(String value) {
                            this.value = value;
                        }

                        /**
                         * Gets the value of the numOfWrongAnswers property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link Byte }
                         *     
                         */
                        public Byte getNumOfWrongAnswers() {
                            return numOfWrongAnswers;
                        }

                        /**
                         * Sets the value of the numOfWrongAnswers property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link Byte }
                         *     
                         */
                        public void setNumOfWrongAnswers(Byte value) {
                            this.numOfWrongAnswers = value;
                        }

                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="user" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="birthDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="idUser" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="role" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "user"
    })
    public static class Users {

        protected List<XmlDB.Users.User> user;

        /**
         * Gets the value of the user property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the user property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUser().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XmlDB.Users.User }
         * 
         * 
         */
        public List<XmlDB.Users.User> getUser() {
            if (user == null) {
                user = new ArrayList<XmlDB.Users.User>();
            }
            return this.user;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="birthDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="idUser" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="role" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "username",
            "email",
            "birthDate",
            "password"
        })
        public static class User {

            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected String username;
            @XmlElement(required = true)
            protected String email;
            @XmlElement(required = true)
            protected String birthDate;
            @XmlElement(required = true)
            protected String password;
            @XmlAttribute(name = "idUser")
            protected Byte idUser;
            @XmlAttribute(name = "role")
            protected String role;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the username property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUsername() {
                return username;
            }

            /**
             * Sets the value of the username property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUsername(String value) {
                this.username = value;
            }

            /**
             * Gets the value of the email property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEmail() {
                return email;
            }

            /**
             * Sets the value of the email property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEmail(String value) {
                this.email = value;
            }

            /**
             * Gets the value of the birthDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBirthDate() {
                return birthDate;
            }

            /**
             * Sets the value of the birthDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBirthDate(String value) {
                this.birthDate = value;
            }

            /**
             * Gets the value of the password property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPassword() {
                return password;
            }

            /**
             * Sets the value of the password property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPassword(String value) {
                this.password = value;
            }

            /**
             * Gets the value of the idUser property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getIdUser() {
                return idUser;
            }

            /**
             * Sets the value of the idUser property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setIdUser(Byte value) {
                this.idUser = value;
            }

            /**
             * Gets the value of the role property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRole() {
                return role;
            }

            /**
             * Sets the value of the role property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRole(String value) {
                this.role = value;
            }

        }

    }

}
