//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.17 at 09:41:51 PM WEST 
//


package models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}correctAnswer"/>
 *         &lt;element ref="{}wrongAnswer"/>
 *       &lt;/sequence>
 *       &lt;attribute name="idQAsked" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="refIdQ" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "correctAnswer",
    "wrongAnswer"
})
@XmlRootElement(name = "qAsked")
public class QAsked {

    @XmlElement(required = true)
    protected CorrectAnswer correctAnswer;
    @XmlElement(required = true)
    protected WrongAnswer wrongAnswer;
    @XmlAttribute(name = "idQAsked")
    protected Integer idQAsked;
    @XmlAttribute(name = "refIdQ")
    protected Integer refIdQ;

    /**
     * Gets the value of the correctAnswer property.
     * 
     * @return
     *     possible object is
     *     {@link CorrectAnswer }
     *     
     */
    public CorrectAnswer getCorrectAnswer() {
        return correctAnswer;
    }

    /**
     * Sets the value of the correctAnswer property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorrectAnswer }
     *     
     */
    public void setCorrectAnswer(CorrectAnswer value) {
        this.correctAnswer = value;
    }

    /**
     * Gets the value of the wrongAnswer property.
     * 
     * @return
     *     possible object is
     *     {@link WrongAnswer }
     *     
     */
    public WrongAnswer getWrongAnswer() {
        return wrongAnswer;
    }

    /**
     * Sets the value of the wrongAnswer property.
     * 
     * @param value
     *     allowed object is
     *     {@link WrongAnswer }
     *     
     */
    public void setWrongAnswer(WrongAnswer value) {
        this.wrongAnswer = value;
    }

    /**
     * Gets the value of the idQAsked property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdQAsked() {
        return idQAsked;
    }

    /**
     * Sets the value of the idQAsked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdQAsked(Integer value) {
        this.idQAsked = value;
    }

    /**
     * Gets the value of the refIdQ property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRefIdQ() {
        return refIdQ;
    }

    /**
     * Sets the value of the refIdQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRefIdQ(Integer value) {
        this.refIdQ = value;
    }

}
